# Generated by Django 4.2.16 on 2024-10-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.CharField(default='Amazon', max_length=100),
        ),
    ]
