# Generated by Django 4.2.16 on 2024-10-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.CharField(max_length=100),
        ),
    ]
